version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    init: true
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        ROOT_PWD: ${DB_ROOT_PWD}
        USER: ${DB_USER}
        USER_PWD: ${DB_USER_PWD}
    image: mariadb:42
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - Inception
    init: true
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - Inception
    init: true
    restart: always

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/jchevet/data/wp_data
      type: 'none'
      o: 'bind'
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/jchevet/data/db_data
      type: 'none'
      o: 'bind'

networks: 
  Inception:
    name: Inception
    driver: bridge