version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PWD=$DB_ROOT_PWD 
    image: mariadb:42
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - Inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=jchevet
      - WORDPRESS_DB_PASSWORD=pwd
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: wordpressdata
      type: none
      o: bind
  dbdata:
    name: dbdata
    driver_opts:
      device: dbdata
      type: none
      o: bind

networks: 
  Inception:
    name: Inception
    driver: bridge