version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    init: true
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        ROOT_PWD: ${DB_ROOT_PWD}
        USER: ${DB_USER}
        USER_PWD: ${DB_USER_PWD}
    image: mariadb:42
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - Inception
    init: true
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file:
      - .env
    # environment:
    #   - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
    #   - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    #   - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
    #   - WORDPRESS_DB_PASS=$WORDPRESS_DB_PASS

    #   - WORDPRESS_ADMIN=$WORDPRESS_ADMIN
    #   - WORDPRESS_ADMIN_PASSWORD=$WORDPRESS_ADMIN_PASSWORD
    #   - WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
    #   - WORDPRESS_USER=$WORDPRESS_USER
    #   - WORDPRESS_USER_PWD=$WORDPRESS_USER_PWD
    #   - WORDPRESS_USER_EMAIL=$WORDPRESS_USER_EMAIL
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    init: true
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/jchevet/mygit/Inception/srcs/wordpressdata
      type: 'none'
      o: 'bind'
  dbdata:
    name: dbdata
    driver: local
    driver_opts:
      device: /Users/jchevet/mygit/Inception/srcs/dbdata
      type: 'none'
      o: 'bind'

networks: 
  Inception:
    name: Inception
    driver: bridge